import type { Playbook, Workflow } from "@/types";

export const PLAYBOOKS: Playbook[] = [
  {
    id: "pb_001",
    slug: "revenue-intelligence-pipeline",
    title: "Revenue Intelligence Pipeline",
    description: "Automatically research prospects, score leads, draft personalised outreach and log everything to your CRM — without touching a keyboard.",
    longDescription: "This 7-agent pipeline connects your CRM, LinkedIn, web research, and email drafting into one seamless loop. It monitors new inbound leads, enriches each record with deep company research, computes an ICP score, generates a personalised outreach email, schedules a follow-up sequence, and posts a Slack summary to your sales channel.",
    category: "revenue-ops",
    complexity: "standard",
    author: { name: "safyr Team", org: "safyr", verified: true },
    tags: ["CRM", "Lead Scoring", "Outreach", "Slack", "Automation"],
    agentCount: 7,
    stepCount: 24,
    avgRuntime: "~4 min",
    timeSaved: "14 hrs/week",
    runCount: 4821,
    starCount: 312,
    cloneCount: 893,
    createdAt: "2024-10-01",
    updatedAt: "2025-02-14",
    featured: true,
    isPremium: false,
    outcomes: [
      "Lead enrichment with 20+ data points",
      "ICP score 0–100",
      "Personalised email draft per lead",
      "CRM record updated automatically",
      "Slack digest every morning",
    ],
    requiredIntegrations: ["Salesforce", "LinkedIn", "Gmail", "Slack"],
  },
  {
    id: "pb_002",
    slug: "contract-review-assistant",
    title: "Contract Review Assistant",
    description: "Upload any contract and get a structured risk report, redline suggestions, and a plain-English summary — in under 2 minutes.",
    category: "legal",
    complexity: "advanced",
    author: { name: "Lexara AI", verified: true },
    tags: ["Legal", "Document Analysis", "Risk", "Compliance"],
    agentCount: 4,
    stepCount: 12,
    avgRuntime: "~2 min",
    timeSaved: "8 hrs/week",
    runCount: 2103,
    starCount: 287,
    cloneCount: 441,
    createdAt: "2024-11-15",
    updatedAt: "2025-02-01",
    featured: true,
    isPremium: true,
    outcomes: [
      "Risk clause identification",
      "Redline suggestions with rationale",
      "Plain-English executive summary",
      "Compliance flag report",
    ],
    requiredIntegrations: ["Google Drive", "Notion"],
  },
  {
    id: "pb_003",
    slug: "customer-health-monitor",
    title: "Customer Health Monitor",
    description: "Daily agent sweep across product usage, support tickets, and NPS to surface at-risk accounts before they churn.",
    category: "customer-success",
    complexity: "standard",
    author: { name: "safyr Team", org: "safyr", verified: true },
    tags: ["Churn Prevention", "NPS", "Support", "Product Usage"],
    agentCount: 5,
    stepCount: 18,
    avgRuntime: "~6 min",
    timeSaved: "10 hrs/week",
    runCount: 3340,
    starCount: 198,
    cloneCount: 621,
    createdAt: "2024-09-20",
    updatedAt: "2025-01-30",
    featured: false,
    isPremium: false,
    outcomes: [
      "Churn risk score per account",
      "Proactive CSM task creation",
      "Weekly health digest",
    ],
    requiredIntegrations: ["Salesforce", "Intercom", "Mixpanel"],
  },
  {
    id: "pb_004",
    slug: "finance-close-accelerator",
    title: "Month-End Close Accelerator",
    description: "Reconcile accounts, flag anomalies, generate variance commentary and prepare board-ready financial summaries automatically.",
    category: "finance",
    complexity: "advanced",
    author: { name: "Decimal Works", verified: true },
    tags: ["Finance", "Reconciliation", "Reporting", "ERP"],
    agentCount: 6,
    stepCount: 31,
    avgRuntime: "~12 min",
    timeSaved: "20 hrs/month",
    runCount: 987,
    starCount: 154,
    cloneCount: 203,
    createdAt: "2024-12-01",
    updatedAt: "2025-02-10",
    featured: false,
    isPremium: true,
    outcomes: [
      "Automated reconciliation across GL accounts",
      "Anomaly detection with explanations",
      "Variance commentary in plain English",
      "Board-ready PDF export",
    ],
    requiredIntegrations: ["QuickBooks", "NetSuite", "Google Sheets"],
  },
  {
    id: "pb_005",
    slug: "candidate-screening-pipeline",
    title: "Candidate Screening Pipeline",
    description: "Parse CVs, score candidates against your job spec, schedule screenings and send personalised status emails — hands-free.",
    category: "hr-ops",
    complexity: "starter",
    author: { name: "PeopleFlow", verified: false },
    tags: ["Recruiting", "CV Parsing", "Scheduling", "HR"],
    agentCount: 3,
    stepCount: 9,
    avgRuntime: "~1 min",
    timeSaved: "6 hrs/week",
    runCount: 5621,
    starCount: 423,
    cloneCount: 1102,
    createdAt: "2024-08-10",
    updatedAt: "2025-02-20",
    featured: true,
    isPremium: false,
    outcomes: [
      "CV parsed and scored in seconds",
      "Candidate ranked against JD criteria",
      "Automatic interview scheduling",
      "Status email sent to each candidate",
    ],
    requiredIntegrations: ["Greenhouse", "Google Calendar", "Gmail"],
  },
  {
    id: "pb_006",
    slug: "content-publishing-engine",
    title: "Content Publishing Engine",
    description: "Brief → Research → Draft → Edit → Publish. A 5-agent content pipeline that ships SEO-optimised posts across your channels.",
    category: "marketing",
    complexity: "standard",
    author: { name: "safyr Team", org: "safyr", verified: true },
    tags: ["SEO", "Content", "Publishing", "Social"],
    agentCount: 5,
    stepCount: 16,
    avgRuntime: "~8 min",
    timeSaved: "12 hrs/week",
    runCount: 7841,
    starCount: 541,
    cloneCount: 1834,
    createdAt: "2024-07-15",
    updatedAt: "2025-02-15",
    featured: true,
    isPremium: false,
    outcomes: [
      "SEO-researched long-form article",
      "Social media variants (LinkedIn, X, Threads)",
      "Meta description and title tags",
      "Scheduled publishing to CMS",
    ],
    requiredIntegrations: ["Webflow", "WordPress", "Buffer"],
  },
  {
    id: "pb_007",
    slug: "data-quality-watchdog",
    title: "Data Quality Watchdog",
    description: "Continuous agent that monitors your data pipelines, detects schema drift and anomalies, and pages your team before data consumers notice.",
    category: "data-ops",
    complexity: "advanced",
    author: { name: "Dataware Labs", verified: true },
    tags: ["Data Quality", "Monitoring", "Alerting", "dbt", "Snowflake"],
    agentCount: 4,
    stepCount: 14,
    avgRuntime: "~2 min",
    timeSaved: "15 hrs/week",
    runCount: 1204,
    starCount: 176,
    cloneCount: 289,
    createdAt: "2025-01-05",
    updatedAt: "2025-02-18",
    featured: false,
    isPremium: true,
    outcomes: [
      "Schema drift detection",
      "Row count anomaly alerts",
      "PagerDuty / Slack incident creation",
      "Root cause summary report",
    ],
    requiredIntegrations: ["Snowflake", "dbt Cloud", "PagerDuty"],
  },
  {
    id: "pb_008",
    slug: "engineering-incident-responder",
    title: "Incident Response Autopilot",
    description: "When an alert fires, this agent gathers logs, correlates recent deploys, drafts a postmortem and notifies stakeholders — all before your on-call engineer has opened their laptop.",
    category: "engineering",
    complexity: "advanced",
    author: { name: "Reliably", verified: true },
    tags: ["Incident Response", "DevOps", "Observability", "On-call"],
    agentCount: 6,
    stepCount: 22,
    avgRuntime: "~3 min",
    timeSaved: "8 hrs/month",
    runCount: 2891,
    starCount: 334,
    cloneCount: 712,
    createdAt: "2024-11-01",
    updatedAt: "2025-02-22",
    featured: false,
    isPremium: true,
    outcomes: [
      "Automated log correlation",
      "Deploy attribution",
      "Stakeholder notifications",
      "Draft postmortem in Notion/Confluence",
    ],
    requiredIntegrations: ["PagerDuty", "Datadog", "GitHub", "Slack"],
  },
];

export const FEATURED_PLAYBOOKS = PLAYBOOKS.filter((p) => p.featured);

export const WORKFLOWS: Workflow[] = [
  {
    id: "wf_001",
    title: "Lead Enrichment Bot",
    description: "Enriches new Salesforce leads with LinkedIn data, ICP score and outreach email",
    status: "active",
    createdAt: "2025-01-15",
    updatedAt: "2025-02-20",
    lastRunAt: "2025-02-21T14:30:00Z",
    runCount: 124,
    playbookId: "pb_001",
    nodes: [],
    edges: [],
  },
  {
    id: "wf_002",
    title: "Blog Publisher v2",
    description: "Brief to published post in under 10 minutes",
    status: "active",
    createdAt: "2025-01-28",
    updatedAt: "2025-02-19",
    lastRunAt: "2025-02-20T09:12:00Z",
    runCount: 47,
    playbookId: "pb_006",
    nodes: [],
    edges: [],
  },
  {
    id: "wf_003",
    title: "CV Screener — Senior Engineer",
    description: "Screens incoming CVs for Senior Eng role at Acme Corp",
    status: "paused",
    createdAt: "2025-02-01",
    updatedAt: "2025-02-18",
    lastRunAt: "2025-02-18T16:45:00Z",
    runCount: 89,
    playbookId: "pb_005",
    nodes: [],
    edges: [],
  },
  {
    id: "wf_004",
    title: "Contract Reviewer Draft",
    description: "Work-in-progress legal contract review workflow",
    status: "draft",
    createdAt: "2025-02-10",
    updatedAt: "2025-02-21",
    runCount: 0,
    nodes: [],
    edges: [],
  },
];

export const CATEGORY_META: Record<string, { label: string; color: string; bg: string }> = {
  "revenue-ops": { label: "Revenue Ops", color: "#2563EB", bg: "#EFF6FF" },
  "legal": { label: "Legal", color: "#7C3AED", bg: "#F5F3FF" },
  "hr-ops": { label: "HR Ops", color: "#059669", bg: "#ECFDF5" },
  "customer-success": { label: "Customer Success", color: "#D97706", bg: "#FEF3C7" },
  "finance": { label: "Finance", color: "#0891B2", bg: "#ECFEFF" },
  "engineering": { label: "Engineering", color: "#DC2626", bg: "#FEF2F2" },
  "marketing": { label: "Marketing", color: "#BE185D", bg: "#FDF2F8" },
  "data-ops": { label: "Data Ops", color: "#65A30D", bg: "#F7FEE7" },
};
